from django.db import models
from django.contrib.postgres.fields import ArrayField

class Food(models.Model):
    name = models.CharField(max_length=50, primary_key = True)
    amount = models.FloatField()

class Reciept(models.Model):
    #use autogenerated id as primary key 
    total_spent = models.FloatField()
    #date/time is the date/time that the receipt was scanned
    date = models.DateTimeField()
    #add day of the week functionality later
    items = models.ManyToManyField(Food)

class Survey(models.Model):
    receipt = models.ManyToManyField(Reciept)
    items = models.ManyToManyField(Food)


